/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dialog: typeof import('./../src/components/fake-window/window-dialog/dialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    FakeWindowItem: typeof import('./../src/components/fake-window/fake-window-item.vue')['default']
    ListItem: typeof import('./../src/components/fake-window/side-list/list-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideList: typeof import('./../src/components/fake-window/side-list/side-list.vue')['default']
  }
}
